@startuml
'https://plantuml.com/class-diagram

title Adapter Pattern

interface Sirializer {
+ String sirialize(String data)
+ String desirialize()
}

class Adapter {
}

class JsonSerializer {

}



@enduml